### ISSUE TITLE
Extreme button does not light up but is still functional

### ISSUE THREAD

**Issue by GlItChEdV0iDz** [Based-Games/BoomerangNet-Cyclon#4]
Extreme button plays the animation along with showing the indicator in the play zone, but the texture does not change to signify that extreme is available. Button is also functional and only when pressed does the texture change.  
![Screenshot_3](https://user-images.githubusercontent.com/127284936/233873790-9ea18523-da94-4a45-8940-d3f959b70eda.jpg)

**Comment by trmazi** [comment]
Resolved in V1.202
