### ISSUE TITLE
Haus Mix - Stage Cleared Leaderboard Variable Overflow

### ISSUE THREAD

**Issue by WooZyDice** [Based-Games/BoomerangNet-Cyclon#8]
Date - May 9th 2023
Game Version - V1.32
OS - Windows 10

When viewing the Haus Mix Stage Cleared screen, expand the leaderboard to view score values.

The website Haus Mix score for WooZy shows:
2,151,708,000

![image](https://github.com/Based-Games/BoomerangNet-Cyclon/assets/90928705/15dcfafc-a0fd-4076-aced-129e4aa02029)

The score value for WooZy in the Haus Mix Stage Cleared screen shows:
-2143259296

![9QrsSua](https://github.com/Based-Games/BoomerangNet-Cyclon/assets/90928705/4cd5e0ec-d2ba-4dbd-bdc7-be7b7958e1c1)

**Comment by trmazi** [comment]
That's a first. Well, I need to completely fix the ranking calculation. I guess this is a good time to do so 😅

**Comment by 6745** [comment]
HAHHAHAHAH CALLED IT!!

**Comment by trmazi** [comment]
This was fixed a while ago, never updated the issue.
